import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import OverlayBanner from "../components/OverlayBanner/OverlayBanner";
import ReferBanner from "@/components/ReferBanner/ReferBanner";
import TopFooter from "../components/TopFooter/TopFooter";
import GetHelp from "../components/GetHelp/GetHelp";
import MobileNav from "../components/MobileNav/MobileNav";

const openSansItalic = localFont({
  src: "./fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf",
  variable: "--font-open-sans-italic",
  weight: "300 900",
});
const openSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf",
  variable: "--font-open-sans",
  weight: "300 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${openSansItalic.variable} antialiased `}
      >
        <Header />
        <MobileNav />
        <OverlayBanner />
        <GetHelp />

        <main className={`xl:mt-24 xl:py-14 2xl:mt-44 2xl:py-20`}>
          {children}
        </main>
        <ReferBanner />
        <TopFooter />
        <Footer />
      </body>
    </html>
  );
}
